# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbb5d64df957e7edb830814bbfccf0acb4589e1b4b3e997c590a6efb68e2eeef1c5f5b829a19f194ec3fd808b9c87f76869ad6a419f66cfc5716dd1766e6f35b

test:
  secret_key_base: 0c4b84549bd7766b3265f0e087354de91a094f4db16d9fb51ab0678e1aecba45fbc994a37acbd0be710b6f95cbb57043087b34a50dd1dd73241b7fc13e477e55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
